spring.application.name=OrderService

server.port=8082

spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true


#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers=${KAFKA_URI:http://localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.template.default-topic=orderTopic

# Consumer properties
spring.kafka.consumer.group-id=zion-group
spring.kafka.consumer.auto-offset-reset=earliest

# Producer properties
spring.kafka.producer.retries=3
spring.kafka.producer.acks=all

#For actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.config.default.registerHealthIndicator=true


logging.file.name=/logs/zion.log
logging.level.root=INFO
#logging.level.org.springframework=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Send logs to Logstash
logging.logback.appender.logstash.destination=localhost:5044
